parameters:
#    vk.example.class: Ailove\VKBundle\Example

services:
    vk.oauth.proxy:
        class: %vk.oauth_proxy_class%
        file: %vk.oauth_proxy_file%
        arguments: 
            clientId: %vk.app_id% 
            clientSecret: %vk.app_secret%
            accessTokenUrl: %vk.access_token_url%
            dialogUrl: %vk.dialog_url%
            responseType: 'code'
            redirectUri: %vk.redirect_uri% 
            scope: %vk.scope%
        calls: 
            - [ setContainer, [ '@service_container' ] ]
    vk.api:
        class: 'VkPhpSdk'
        file: %vk.sdk_file%
    vk.user.provider: 
        class: 'Ailove\VKBundle\Security\User\VKUserProvider'
        arguments: [ '@vk.oauth.proxy', '@fos_user.user_manager' ]
    vk.auth.provider:
        class: 'Ailove\VKBundle\Security\Authentication\Provider\VKProvider'
        arguments: [ '@vk.oauth.proxy', '@vk.user.provider', '@security.user_checker' ]
    vk.firewall.listener:
        class: 'Ailove\VKBundle\Security\Firewall\VKListener'
        parent: security.authentication.listener.abstract
        abstract: true
