parameters:
    vk_api_sig_helper.class: Ailove\VKApiHelperBundle\Helper\SigHelper
    vk_api_helper.class: Ailove\VKApiHelperBundle\Helper\ApiHelper

services:
    vk_api_sig_helper:
        class: %vk_api_sig_helper.class%
    vk_api_helper:
        class: %vk_api_helper.class%
        arguments: [ '@vk.oauth.proxy', '@vk.api', '@vk_api_sig_helper' ]
    vk_api_helper.message:
        class: Ailove\VKApiHelperBundle\Admin\MessageAdmin
        calls:
            - [ setTranslationDomain, [ 'VKApiHelperBundle' ] ]          
        tags:
          - { name: sonata.admin, manager_type: orm, group: notices, label: message }
        arguments: [null, Ailove\VKApiHelperBundle\Entity\Message, VKApiHelperBundle:MessageAdmin]        
    vk_api_helper.notice_queue:
        class: Ailove\VKApiHelperBundle\Admin\NoticeQueueAdmin
        calls:
            - [ setTranslationDomain, [ 'VKApiHelperBundle' ] ]          
        tags:
          - { name: sonata.admin, manager_type: orm, group: notices, label: notices_queue }
        arguments: [null, Ailove\VKApiHelperBundle\Entity\NoticeQueue, VKApiHelperBundle:NoticeQueueAdmin]
