parameters:
#    ok.example.class: Ailove\OKBundle\Example

services:
    ok.oauth.proxy:
        class: %ok.oauth_proxy_class%
        arguments: 
            clientId: %ok.app_id% 
            clientSecret: %ok.app_secret%
            accessTokenUrl: %ok.access_token_url%
            dialogUrl: %ok.dialog_url%
            responseType: 'code'
            redirectUri: %ok.redirect_uri% 
            scope: %ok.scope%
        calls: 
            - [ setContainer, [ '@service_container' ] ]
            - [ setSdk, [ '@ok.api' ] ]
    ok.api:
        class: 'OkPhpSdk'
#        file: %ok.sdk_file%
        arguments:
            clientId: %ok.app_id% 
            clientSecret: %ok.app_secret%
            appPublicKey: %ok.app_public_key%
    ok.user.provider: 
        class: 'Ailove\OKBundle\Security\User\OKUserProvider'
        arguments: [ '@ok.oauth.proxy', '@fos_user.user_manager' ]
    ok.auth.provider:
        class: 'Ailove\OKBundle\Security\Authentication\Provider\OKProvider'
        arguments: [ '@ok.oauth.proxy', '@ok.user.provider', '@security.user_checker' ]
    ok.firewall.listener:
        class: 'Ailove\OKBundle\Security\Firewall\OKListener'
        parent: security.authentication.listener.abstract
        abstract: true
