Ailove\VKApiHelperBundle\Entity\Message:
    type: entity
    table: notices_messages           
    repositoryClass: Ailove\VKApiHelperBundle\Entity\MessageRepository
    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }
    fields:
        text:
            type: text
            nullable: true
    lifecycleCallbacks: []