Ailove\VKApiHelperBundle\Entity\NoticeQueue:
    type: entity
    table: notices_queue
    repositoryClass: Ailove\VKApiHelperBundle\Entity\NoticeQueueRepository
    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }
    fields:
        createAt:
            type: datetime
            column: create_at
            nullable: true
        status:
            type: integer
            nullable: true
    manyToOne:
        message:
            targetEntity: Ailove\VKApiHelperBundle\Entity\Message
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
                name: user_id
    lifecycleCallbacks: 
        prePersist: [setCreateAtDefault]