# 
# more information can be found here http://sonata-project.org/bundles/user
#
ok:
    app_id: %OK_APP_ID%
    app_secret: %OK_APP_SECRET%
    app_public_key: %OK_PUBLIC_KEY%
    redirect_route: _ok_security_check
    developer_apps:
      sf-2.1-build.lo:
        app_id: 123
        app_secret: secret
