# 
# more information can be found here http://sonata-project.org/bundles/user
#
ok:
    app_id: %OK_APP_ID%
    app_secret: %OK_APP_SECRET%
    app_public_key: %OK_PUBLIC_KEY%
#    access_token_url: 'http://api.odnoklassniki.ru/oauth/token.do'
#    dialog_url: 'http://www.odnoklassniki.ru/oauth/authorize'
    redirect_uri: %OK_REDIRECT_URI%
#    scope: 'VALUABLE ACCESS'
#    oauth_proxy_class: Ailove\OKBundle\Service\OKOauthSessionProxy
#    sdk_file: %kernel.root_dir%/../src/ok-php-sdk/classes/OkPhpSdk.php
