<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../classes/Oauth2Proxy.php';

/**
 * Test class for Oauth2Proxy.
 * Generated by PHPUnit on 2011-08-21 at 15:45:27.
 */
class Oauth2ProxyTest extends PHPUnit_Framework_TestCase
{
	const CLIENT_ID = '2446676';
	const CLIENT_SECRET = 'oawLNhZCTYRjEJ72ZdET';
	const ACCESS_TOKEN_URL = 'https://api.vkontakte.ru/oauth/access_token';
	const DIALOG_URL = 'http://api.vkontakte.ru/oauth/authorize';
	const RESPONSE_TYPE = 'code';
	const REDIRECT_URI = 'http://localhost/vkPhpSdk/example';
	const SCOPE = 'offline,notify,friends,photos,audio,video';
	
	/**
	 * @var Oauth2Proxy
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new TransientOauth2Proxy(
			self::CLIENT_ID,
			self::CLIENT_SECRET,
			self::ACCESS_TOKEN_URL,
			self::DIALOG_URL,
			self::RESPONSE_TYPE,
			self::REDIRECT_URI,
			self::SCOPE
		);		
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		unset($this->object);
	}

	public function testGetAccessToken()
	{
		$this->assertEquals($this->object->getAccessToken(), '533bacf01e11f55b536a565b57531ac114461ae8736d6506a3');
	}
	
	public function testGetExpiresIn()
	{
		$this->assertEquals($this->object->getExpiresIn(), '43200');
	}

	public function testGetUserId()
	{
		$this->assertEquals($this->object->getUserId(), '6492');
	}	
}

class TransientOauth2Proxy extends Oauth2Proxy
{
	const AUTH_JSON = '{"access_token":"533bacf01e11f55b536a565b57531ac114461ae8736d6506a3", "expires_in":43200, "user_id":6492}';
	
	/**
	 * Get authorization JSON string.
	 * 
	 * @return string
	 */
	protected function getAuthJson()
	{
		return self::AUTH_JSON;
	}
}