login_check:
    pattern: /user/login_check/
    defaults: { _controller: 'ApplicationSonataUserBundle:Security:check' }
_social_send_confirm_email:
    pattern: /user/social/confirm/send/
    defaults: { _controller: 'ApplicationSonataUserBundle:SocialConnect:sendSocialBindEmail' }
_social_confirm_bind:
    pattern: /user/social/confirm/bind/{token}/{social}/{socialUid}
    defaults: { _controller: 'ApplicationSonataUserBundle:SocialConnect:socialBind' }
_social_connect:
    pattern: /user/connect/
    defaults: { _controller: 'ApplicationSonataUserBundle:SocialConnect:connect' }
